version: 2
jobs:

  build:
    docker:
      - image: docker:17.06.0-ce

    steps:
      - checkout

      - setup_remote_docker:
          exclusive: false
          reusable: true
          version: 17.06.0-ce

      - run:
          name: Docker build, login, and push
          command: |
            set -x
            TAG=v0.1.$CIRCLE_BUILD_NUM
            docker build --tag="wpsinc/build-server-image:$TAG" ./
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push wpsinc/build-server-image:$TAG
