version: 2
jobs:

  build:
    docker:
      # Primary container image where all steps run.
      - image: docker:17.06.0-ce

    steps:
      - checkout

      - setup_remote_docker:
          version: 17.06.0-ce

      - run:
          name: Docker build, login, and push
          command: |
            set -x
            TAG=v0.1.$CIRCLE_BUILD_NUM
            docker build --tag="wpsinc/build-server-image:$TAG" ./
            docker build --tag="wpsinc/build-server-image:latest" ./
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push wpsinc/build-server-image:$TAG
