version: 2
jobs:

  build:
    branches:
      only:
        - master

    docker:
      - image: docker:stable

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Docker build.
          command: |
            set -x
            docker build --tag="${CIRCLE_PROJECT_REPONAME}" ./

      - run:
          name: Docker tag.
          command: |
            set -x
            docker tag ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-latest
            docker tag ${CIRCLE_PROJECT_REPONAME} ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-v${CIRCLE_BUILD_NUM}

      - deploy:
          name: Docker push.
          command: |
            set -x
            docker push ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-latest
            docker push ${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-v${CIRCLE_BUILD_NUM}
