version: 2
jobs:

  build:
    branches:
      only:
        - master

    docker:
      - image: docker:stable

    environment:
      ECR_URI: 402174392361.dkr.ecr.us-west-2.amazonaws.com

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Docker build.
          command: |
            set -x
            docker build --tag="${CIRCLE_PROJECT_REPONAME}" ./

      - run:
          name: Docker tag.
          command: |
            set -x
            docker tag ${CIRCLE_PROJECT_REPONAME} ${ECR_URI}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-latest
            docker tag ${CIRCLE_PROJECT_REPONAME} ${ECR_URI}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-v${CIRCLE_BUILD_NUM}

      - deploy:
          name: Install the AWS Command Line Interface (CLI).
          command: |
            apk --no-cache add \
            py-pip

            pip install awscli --upgrade

      - deploy:
          name: Get Docker login from ECR and then run the Docker login command.
          command: |
            DOCKER_LOGIN_CMD=`aws ecr get-login --region="us-west-2" --no-include-email`
            ${DOCKER_LOGIN_CMD}

      - deploy:
          name: Docker push.
          command: |
            set -x
            docker push ${ECR_URI}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-latest
            docker push ${ECR_URI}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_BRANCH}-v${CIRCLE_BUILD_NUM}
